#!/bin/sh
if ! command -v openssl >/dev/null 2>&1 ; then
  echo "Error: Could not find openssl in \$PATH: $PATH"
  exit 1
fi

if test -f osintfootprints.key; then
  echo "Error: osintfootprints.key already exists"
  exit 1
fi

if test -f osintfootprints.crt; then
  echo "Error: osintfootprints.crt already exists"
  exit 1
fi

openssl req -new -newkey rsa:4096 -sha256 -x509 -days 365 -nodes -out osintfootprints.crt -keyout osintfootprints.key -subj "/CN=localhost"

chmod 600 osintfootprints.crt
chmod 600 osintfootprints.key
