'use client';

import React, { useState } from 'react';
import {
  FileText, Download, Plus, Brain, File, FileSpreadsheet, FileJson,
  ClipboardList, CheckCircle, Clock, AlertTriangle, Eye
} from 'lucide-react';
import { cn, formatDate, formatDateTime, getStatusColor } from '@/lib/utils';
import { mockCases, mockAIReports } from '@/data/mock-data';
import toast from 'react-hot-toast';

const reportTemplates = [
  { id: 'investigation', name: 'Investigation Report', desc: 'Comprehensive case investigation report', icon: FileText },
  { id: 'evidence', name: 'Evidence Summary', desc: 'Detailed evidence inventory and chain of custody', icon: ClipboardList },
  { id: 'supervisor', name: 'Supervisor Brief', desc: 'Executive summary for supervisory review', icon: Eye },
  { id: 'timeline', name: 'Timeline Report', desc: 'Chronological event report', icon: Clock },
];

const exportFormats = [
  { id: 'pdf', name: 'PDF Report', icon: FileText, desc: 'Professional formatted PDF' },
  { id: 'csv', name: 'CSV Export', icon: FileSpreadsheet, desc: 'Evidence list as spreadsheet' },
  { id: 'json', name: 'JSON Package', icon: FileJson, desc: 'Full case data package' },
  { id: 'custody', name: 'Chain of Custody', icon: ClipboardList, desc: 'Custody log export' },
];

export default function ReportsPage() {
  const [selectedCase, setSelectedCase] = useState(mockCases[0].id);
  const [selectedTemplate, setSelectedTemplate] = useState('investigation');
  const [includeEvidence, setIncludeEvidence] = useState(true);
  const [includeTimeline, setIncludeTimeline] = useState(true);
  const [aiAssisted, setAiAssisted] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [generatedReports, setGeneratedReports] = useState(mockAIReports);

  const handleGenerate = async () => {
    setGenerating(true);
    try {
      // Simulate API call for report generation
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      const templateName = reportTemplates.find(t => t.id === selectedTemplate)?.name || 'Report';
      
      let detailedContent = `# ${templateName} - Case ${selectedCase}\n\n`;
      detailedContent += `**Generated By**: Marcus Wright\n**Date**: ${new Date().toLocaleString()}\n\n`;
      detailedContent += `## 1. Executive Summary\n\nThis report outlines the findings for case ${selectedCase}. The investigation was conducted thoroughly, capturing all relevant artifacts, network telemetry, and forensic evidence required to fully understand the scope of the incident. Initial triage indicates unauthorized access and potential data exfiltration.\n\n`;
      detailedContent += `## 2. Investigation Timeline\n\n- **T0**: Initial alert triggered by SIEM regarding anomalous outbound traffic.\n- **T+2h**: Incident Response team engaged. Affected endpoints isolated.\n- **T+6h**: Memory dumps and disk images captured from compromised servers.\n- **T+24h**: Forensic analysis identifies custom malware payload.\n\n`;
      detailedContent += `## 3. Evidence & Artifacts\n\nSeveral critical artifacts were collected during this investigation:\n- \`svchost_update.exe\` (SHA256: 8f434346648...)\n- Network PCAP files showing C2 communication to 185.220.101.42\n- Decrypted payload configuration files.\n\n`;
      detailedContent += `## 4. Threat Intelligence (OSINT)\n\nThe IP addresses involved have been flagged by multiple threat intelligence feeds as being associated with an Advanced Persistent Threat (APT) group known for targeting defense contractors.\n\n`;
      detailedContent += `## 5. Next Steps & Recommendations\n\n1. Rotate all administrative credentials immediately.\n2. Implement strict network segmentation for critical servers.\n3. Deploy updated YARA rules to EDR solutions to detect similar payloads.\n4. Continue monitoring for lateral movement.\n\n`;
      detailedContent += `---\n*Report generated ${aiAssisted ? 'with Aegis Sandbox AI assistance' : 'manually'}.*`;

      const newReport = {
        id: `air-${Date.now()}`,
        case_id: selectedCase,
        report_type: selectedTemplate as any,
        content: detailedContent,
        generated_by: 'Marcus Wright',
        generated_at: new Date().toISOString(),
        confidence: 95,
        model: 'Aegis Core v1.4',
        status: 'draft' as const
      };
      
      setGeneratedReports(prev => [newReport, ...prev]);
      toast.success(`${reportTemplates.find(t => t.id === selectedTemplate)?.name || 'Report'} generated successfully!`);
    } catch (error) {
      toast.error('Error generating report. Please try again.');
      console.error(error);
    } finally {
      setGenerating(false);
    }
  };

  const handleDownload = (reportName: string, content?: string) => {
    try {
      const reportHtml = `
        <html>
          <head>
            <title>${reportName}</title>
            <style>
              body { font-family: sans-serif; padding: 40px; color: #111; max-width: 800px; margin: 0 auto; }
              h1 { color: #333; text-transform: capitalize; }
              .content { margin-top: 20px; white-space: pre-wrap; font-family: monospace; font-size: 14px; background: #f9f9f9; padding: 20px; border-radius: 8px; border: 1px solid #eee; }
            </style>
          </head>
          <body>
            <h1>${reportName}</h1>
            <p>Generated on ${new Date().toLocaleString()}</p>
            <hr/>
            ${content ? `<div class="content">${content}</div>` : '<p>This is an auto-generated official report for the Aegis CIIP platform.</p>'}
          </body>
        </html>
      `;
      const blob = new Blob([reportHtml], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${reportName.replace(/\s+/g, '_')}_${new Date().getTime()}.html`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      toast.success(`${reportName} downloaded successfully.`);
    } catch (error) {
      toast.error('Error downloading report.');
      console.error(error);
    }
  };

  const handleExport = (fmtId: string, fmtName: string) => {
    try {
      let content = '';
      let type = '';
      let extension = '';
      
      switch (fmtId) {
        case 'csv':
          content = 'ID,Evidence Number,File Name,Type,Size,Hash\n1,EV-001,server_logs.zip,Archive,50MB,8f434346648...\n2,EV-002,memdump.raw,Memory,8GB,a1b2c3d4e5f...';
          type = 'text/csv';
          extension = 'csv';
          break;
        case 'json':
          content = JSON.stringify({ case_id: selectedCase, status: 'active', evidence_count: 12, flags: ['apt', 'data-exfil'] }, null, 2);
          type = 'application/json';
          extension = 'json';
          break;
        case 'custody':
          content = 'Timestamp,Action,Handler,From,To\n2026-07-21 10:00:00,Acquired,M. Wright,Server Room,Forensic Lab\n2026-07-21 14:30:00,Analyzed,A. Patel,Forensic Lab,Secure Storage';
          type = 'text/csv';
          extension = 'csv';
          break;
        case 'pdf':
        default:
          handleDownload(fmtName, `# Quick Export: ${fmtName}\n\nThis is a highly detailed placeholder for the ${fmtName} export, capturing all relevant data for case ${selectedCase}.`);
          return;
      }

      const blob = new Blob([content], { type });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${fmtName.replace(/\s+/g, '_')}_${new Date().getTime()}.${extension}`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      
      toast.success(`${fmtName} exported successfully.`);
    } catch (error) {
      toast.error('Error exporting data.');
    }
  };

  return (
    <div className="space-y-6 animate-in">
      <div>
        <h1 className="text-2xl font-bold text-white flex items-center gap-3">
          <FileText className="w-7 h-7 text-cyber-accent" />
          Reports
        </h1>
        <p className="text-sm text-cyber-muted mt-1">Generate, export, and manage investigation reports</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Report Generation */}
        <div className="lg:col-span-2 space-y-6">
          {/* Template Selection */}
          <div className="cyber-card-flat">
            <h3 className="text-sm font-semibold text-white mb-4">Report Template</h3>
            <div className="grid grid-cols-2 gap-3">
              {reportTemplates.map(tmpl => {
                const Icon = tmpl.icon;
                return (
                  <button
                    key={tmpl.id}
                    onClick={() => setSelectedTemplate(tmpl.id)}
                    className={cn(
                      'p-4 rounded-xl border text-left transition-all',
                      selectedTemplate === tmpl.id
                        ? 'bg-cyber-accent/10 border-cyber-accent/30'
                        : 'bg-cyber-bg border-cyber-border hover:border-cyber-border-light'
                    )}
                  >
                    <Icon className={cn('w-5 h-5 mb-2',
                      selectedTemplate === tmpl.id ? 'text-cyber-accent' : 'text-cyber-muted'
                    )} />
                    <p className="text-sm font-medium text-cyber-text">{tmpl.name}</p>
                    <p className="text-xs text-cyber-muted mt-0.5">{tmpl.desc}</p>
                  </button>
                );
              })}
            </div>
          </div>

          {/* Configuration */}
          <div className="cyber-card-flat">
            <h3 className="text-sm font-semibold text-white mb-4">Configuration</h3>
            <div className="space-y-4">
              <div>
                <label className="block text-xs font-medium text-cyber-muted mb-1.5 uppercase tracking-wider">Select Case</label>
                <select className="cyber-input" value={selectedCase} onChange={e => setSelectedCase(e.target.value)}>
                  {mockCases.map(c => (
                    <option key={c.id} value={c.id}>{c.case_number} — {c.title}</option>
                  ))}
                </select>
              </div>
              <div className="flex items-center gap-6">
                <label className="flex items-center gap-2 cursor-pointer">
                  <input type="checkbox" checked={includeEvidence} onChange={e => setIncludeEvidence(e.target.checked)} className="w-3.5 h-3.5 rounded border-cyber-border bg-cyber-surface text-cyber-accent" />
                  <span className="text-xs text-cyber-text-dim">Include evidence inventory</span>
                </label>
                <label className="flex items-center gap-2 cursor-pointer">
                  <input type="checkbox" checked={includeTimeline} onChange={e => setIncludeTimeline(e.target.checked)} className="w-3.5 h-3.5 rounded border-cyber-border bg-cyber-surface text-cyber-accent" />
                  <span className="text-xs text-cyber-text-dim">Include timeline</span>
                </label>
                <label className="flex items-center gap-2 cursor-pointer">
                  <input type="checkbox" checked={aiAssisted} onChange={e => setAiAssisted(e.target.checked)} className="w-3.5 h-3.5 rounded border-cyber-border bg-cyber-surface text-cyber-accent" />
                  <span className="text-xs text-cyber-text-dim">AI-assisted draft</span>
                </label>
              </div>

              <div className="flex gap-3">
                <button onClick={handleGenerate} className="cyber-btn-primary" disabled={generating}>
                  {generating ? (
                    <>
                      <div className="w-4 h-4 border-2 border-black/30 border-t-black rounded-full animate-spin" />
                      Generating...
                    </>
                  ) : (
                    <>
                      <Brain className="w-4 h-4" /> Generate Report
                    </>
                  )}
                </button>
              </div>
            </div>
          </div>

          {/* Generated Reports */}
          <div className="cyber-card-flat">
            <h3 className="text-sm font-semibold text-white mb-4">Generated Reports</h3>
            <div className="space-y-3">
              {generatedReports.map(report => (
                <div key={report.id} className="flex items-center justify-between p-3 bg-cyber-bg rounded-lg border border-cyber-border hover:border-cyber-border-light transition-colors">
                  <div className="flex items-center gap-3">
                    <FileText className="w-5 h-5 text-cyber-muted" />
                    <div>
                      <p className="text-sm text-cyber-text capitalize">{report.report_type.replace('_', ' ')}</p>
                      <p className="text-[10px] text-cyber-muted">Generated {formatDateTime(report.generated_at)}</p>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    <span className={cn('cyber-badge text-[10px]', getStatusColor(report.status))}>{report.status}</span>
                    <button 
                      onClick={() => handleDownload(report.report_type.replace('_', ' '), report.content)}
                      className="cyber-btn-ghost p-1.5"
                      title="Download Report"
                    >
                      <Download className="w-4 h-4" />
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Export Options */}
        <div className="space-y-6">


          <div className="cyber-card-flat">
            <h3 className="text-sm font-semibold text-white mb-3">AI Advisory</h3>
            <div className="bg-amber-500/5 border border-amber-500/20 rounded-lg p-3">
              <div className="flex items-start gap-2">
                <AlertTriangle className="w-4 h-4 text-amber-400 flex-shrink-0 mt-0.5" />
                <p className="text-xs text-amber-400/80 leading-relaxed">
                  AI-generated reports are advisory only. All findings must be independently verified before use in legal proceedings or official documentation.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
